### ISSUE TITLE
precision t3620 BIOS 2.19.0 (newer 2.21.0 now) missing

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#100]
precision+t3620
LVFS version  2.18.1
https://fwupd.org/lvfs/search?value=precision+3620
Dell version 09 Nov 2021,2.19.0, 2.19.0
https://www.dell.com/support/home/en-us/product-support/product/precision-t3620-workstation/drivers

**Comment by pjwelsh** [comment]
Now the next Urgent version has changed:
Dell version 07 Jan 2022,2.20.0, 2.20.0
https://www.dell.com/support/home/en-us/product-support/product/precision-t3620-workstation/drivers

**Comment by pjwelsh** [comment]
@dell-client-linux please update to latest dell "Urgent".

**Comment by pjwelsh** [comment]
Update still missing.

**Comment by pjwelsh** [comment]
@dell-client-linux Please update as soon as possible. This will be the third update missed BIOS from the original post if not:
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=yfjyj&oscode=wb64a&productcode=precision-t3620-workstation

**Comment by sunnycrown83** [comment]
@pjwelsh under working, will solve it asap.

**Comment by pjwelsh** [comment]
@sunnycrown83 any update on this missing firmware? Two weeks have passed since your response of "... will solve asap".

**Comment by fuqian2022** [comment]
@pjwelsh , Sorry for the late response. 
BIOS team is working on uploading the new release to LVFS. Target release date: May 4th.

**Comment by pjwelsh** [comment]
Thank you for the update.
You may already know, but a significant number of "urgent" BIOS updates were just released in the last day (optiplex-5060 optiplex-3040m optiplex-7060 optiplex-3060 optiplex-7070 optiplex-5070 etc)

**Comment by pjwelsh** [comment]
@sunnycrown83 any update on the new timeline as the May 4th noted target has passed?

**Comment by fuqian2022** [comment]
@pjwelsh, Sorry for the delay. 2.21.0 has been released to LVFS site.

**Comment by pjwelsh** [comment]
I can confirm that the BIOS update both is showing and updates as expected on the systems I've tested with. Thank you very much for your help on this.
