### ISSUE TITLE
Latitude 3410 BIOS missing 1.12.0

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#110]
latitude+3410
LVFS version  1.10.1
https://fwupd.org/lvfs/search?value=latitude+3410
Dell version 29 Dec 2021,1.12.0, 1.12.0
https://www.dell.com/support/home/en-us/product-support/product/latitude-14-3410-laptop/drivers

**Comment by pjwelsh** [comment]
@dell-client-linux please update to latest dell "Urgent".

**Comment by pjwelsh** [comment]
Someone from Dell should really be paying attention to missing updates. Anyone representing Dell looking at these?

**Comment by hughsie** [comment]
@dell-client-linux is forwarding them to the internal teams, I hope.

**Comment by sunnycrown83** [comment]
@pjwelsh Expect to be ready soon, Dell internal is working on that. And a new process in under setup and will keep firmware updated in the near future.

**Comment by sunnycrown83** [comment]
@hughsie Does the LVFS server work now? ODM told me "Internal Sever Error" shown after he saved description information.

**Comment by sunnycrown83** [comment]
> @hughsie Does the LVFS server work now? ODM told me "Internal Sever Error" shown after he saved description information.

Please ignore this comment, 1.13.0 has been there.

**Comment by pjwelsh** [comment]
The newest (1.13.0) does appear on the site and is showing in fwupdmgr. Thank you for your actions. closing

**Comment by pjwelsh** [comment]
Just a quick note to make sure that the significant list of outdated BIOS/firmware issues are going to also be addressed?
I will check my script to see which are currently outstanding and comment/close accordingly.
