### ISSUE TITLE
Latitude 5521 / Precision 3561 Bios outdated

### ISSUE THREAD

**Issue by Thalience** [fwupd/firmware-dell#128]
Latitude 5521

LVFS has version [1.5.3](https://fwupd.org/lvfs/devices/com.dell.uefi9a5fa06d.firmware)

Latest version from Dell is [1.11.1](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=2p48h&oscode=wt64a&productcode=latitude-15-5521-laptop)

**Comment by CragW** [comment]
1.13.0 released to LVFS.
