### ISSUE TITLE
Dell latitude 7490 missing urgent BIOS update

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#138]
LVFS version  23.00
https://fwupd.org/lvfs/search?value=latitude+7490

Dell version 16 Aug 2022,1.27.0, 1.27.0
https://www.dell.com/support/home/en-us/product-support/product/latitude-14-7490-laptop/drivers
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=tkc9h&oscode=biosa&productcode=latitude-14-7490-laptop

@dell-client-linux

**Comment by pjwelsh** [comment]
@dell-client-linux please update the Latitude 7490 BIOS.

**Comment by pjwelsh** [comment]
@dell-client-linux please update the Latitude 7490 BIOS.

**Comment by chinyakao** [comment]
Hello @pjwelsh ,
The latest 1.28.0 version is updated. Thank you.

**Comment by pjwelsh** [comment]
Please consider "fixing" the meta data for this unit. A search for "latitude 7490" does *NOT* lead to correct information. It leads to a link that says, "Thunderbolt NVM for Latitude 7490 Device Update", but is *actually* a page that says, "Dell Thunderbolt NVM for Latitude 7290".
The other issue with meta data is that in order to actually find a "latitude 7490" you *must know* it is only searchable by being called "latitdue 7x90". Please include specific model numbers in the descriptions or help find a better search mechanism.
Thank you.
BIOS check as updated. closing.
