### ISSUE TITLE
latitude 3510 missing Urgent BIOS update

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#141]
LVFS version  1.17.0
https://fwupd.org/lvfs/search?value=latitude+3510
Dell version 08 Sep 2022,1.18.0, 1.18.0
https://www.dell.com/support/home/en-us/product-support/product/latitude-15-3510-laptop/drivers

**Comment by chinyakao** [comment]
Hi @pjwelsh,
The firmware is updated on LVFS. Thank you for reminder.

**Comment by pjwelsh** [comment]
Thank you very much for the notice! closing.
