### ISSUE TITLE
Missing "critical" BIOS update for Optiplex 3050 1.22.1

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#146]
LVFS version  1.21.0
https://fwupd.org/lvfs/search?value=optiplex+3050
Dell version 17 Oct 2022,1.22.1, 1.22.1
https://www.dell.com/support/home/en-us/product-support/product/optiplex-3050-desktop/drivers
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=pdmh2&oscode=biosa&productcode=optiplex-3050-desktop

**Comment by pjwelsh** [comment]
Thank you for (silently?) updating. closing.

**Comment by hughsie** [comment]
If it helps, I do think Dell reads these.
