### ISSUE TITLE
Dell Latitude 7390 2-in-1: wrong firmware link

### ISSUE THREAD

**Issue by williliebig** [fwupd/firmware-dell#149]
hej, if I want to use fwupd for updating my Dell Latitude 7390 2-in-1 firmware, there are also updates listed of the Dell Latitude E5X60 (https://fwupd.org/lvfs/devices/com.dell.uefi6180aaaa.firmware), so there is no possibility to keep the system up to date automatically.

**Comment by CragW** [comment]
@williliebig, CHID has been added to the firmware releases for platform identification. Please `refresh` the metadata and then `update` system firmware again, let me know how it goes.  :)

**Comment by williliebig** [comment]
thanks! Now, the firmware option for Latitude E5X60 is gone, but up to now no update to the firmware version 0.1.27.0 (the laptop is still on 0.1.26.0) is offered ...

**Comment by CragW** [comment]
@williliebig can you please post the output of `$ sudo fwupdtool hwids`?

**Comment by williliebig** [comment]
of course ... :

`Computer Information
--------------------
BiosVendor: Dell Inc.
BiosVersion: 1.26.0
BiosMajorRelease: 1
BiosMinorRelease: 26
Manufacturer: Dell Inc.
Family: Latitude
ProductName: Latitude 7390 2-in-1
ProductSku: 823
EnclosureKind: 1f
BaseboardManufacturer: Dell Inc.
BaseboardProduct: YNG30

Hardware IDs
------------
{8109e258-f56d-5151-95a1-f0979199b700}   <- Manufacturer + Family + ProductName + ProductSku + BiosVendor + BiosVersion + BiosMajorRelease + BiosMinorRelease
{270958d7-cf07-5c48-9ff5-a9ec4760032c}   <- Manufacturer + Family + ProductName + BiosVendor + BiosVersion + BiosMajorRelease + BiosMinorRelease
{81a00f40-ca5e-5271-831e-2e68f9fc400d}   <- Manufacturer + ProductName + BiosVendor + BiosVersion + BiosMajorRelease + BiosMinorRelease
{01c83204-09c8-5c95-9a67-013d20faf63d}   <- Manufacturer + Family + ProductName + ProductSku + BaseboardManufacturer + BaseboardProduct
{3bd76904-52ce-5167-ad60-944d432a30f7}   <- Manufacturer + Family + ProductName + ProductSku
{20fbd95b-c4aa-58d6-8770-a188e75088ce}   <- Manufacturer + Family + ProductName
{bf337be1-7473-5ac5-ab28-93a7cffedce2}   <- Manufacturer + ProductSku + BaseboardManufacturer + BaseboardProduct
{a0f663f5-2198-5d59-ab0f-17bab79cabe1}   <- Manufacturer + ProductSku
{d443c5f3-41aa-510b-836f-9782f02200ee}   <- Manufacturer + ProductName + BaseboardManufacturer + BaseboardProduct
{c43b5dd4-56fe-5011-bf96-8385d6d99433}   <- Manufacturer + ProductName
{c1a6a155-50eb-5817-90e5-1c112d7a7775}   <- Manufacturer + Family + BaseboardManufacturer + BaseboardProduct
{41b0b5d7-ad12-5d86-9a3d-826f9b20adcc}   <- Manufacturer + Family
{a802e8d7-2e38-5e27-ada9-e5f99cfc2c90}   <- Manufacturer + EnclosureKind
{1c12b68d-1f73-575e-bbbb-8194d9bac332}   <- Manufacturer + BaseboardManufacturer + BaseboardProduct
{85d38fda-fc0e-5c6f-808f-076984ae7978}   <- Manufacturer`

**Comment by williliebig** [comment]
yes, I refreshed the metadata ... unfortunately the new firmware is still not offered. Here my output:
[output.txt](https://github.com/fwupd/firmware-dell/files/10174508/output.txt)

**Comment by CragW** [comment]
I had a realization that Latitude 7390 2-in-1 has limited support for Ubuntu/Linux OS. Please download the system BIOS through dell.com and install it via the script.  For example:

https://www.dell.com/support/home/en-us/product-support/product/latitude-13-7390-2-in-1-laptop/drivers

```
# /usr/share/fwupd/install_dell_bios_exe.py foo.exe
```
