### ISSUE TITLE
Missing Dell XPS 8940 BIOS *CRITICAL*

### ISSUE THREAD

**Issue by JasonMeudt** [fwupd/firmware-dell#155]
The last lvfs available BIOS for the Dell XPS8940 is 2.4, while the most recent is now 2.10 from Dell.

When filing a request please include the following items:

A link to the firmware update at [Dell support](https://support.dell.com/)

https://dl.dell.com/FOLDER08983369M/1/XPS_8940_2.10.0.exe
and/or
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=r69t0&oscode=wt64a&productcode=xps-8940-desktop

A link to the previous firmware upgrade at [LVFS](https://fwupd.org/)

https://fwupd.org/lvfs/devices/com.dell.uefi3794279e.firmware

**Comment by CragW** [comment]
XPS 8940 doesn't support Linux officially hence lvfs upload isn't confirmed, suggest to install BIOS.exe from dell support.
```
# /usr/share/fwupd/install_dell_bios_exe.py foo.exe
```
