### ISSUE TITLE
Support for Dell in-between-versions

### ISSUE THREAD

**Issue by dcd-arnold** [fwupd/firmware-dell#158]
Hi,
thanks for `fwupd`. It makes my life so much better. 

**Describe the question**
I have a Dell OptiPlex 7460 AIO with Bios version 1.5.3. If I run `fwupdmgr update` I see:
```
$ fwupdmgr update
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade System Firmware from 1.5.3 to 1.25.0?                                ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release fixes the following issues: Firmware updates to 2023     ║
║ Jan and Feb platform update.                                                 ║
║                                                                              ║
║ OptiPlex 7460 AIO must remain plugged into a power source for the duration   ║
║ of the update to avoid damage.                                               ║
╚══════════════════════════════════════════════════════════════════════════════╝
```

However, Dell writes the following on [this Bios version's release page](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=9y9k4) (see Additional details > Important Information):
> If the current BIOS version is earlier than 1.6.4, ensure that you update the BIOS to version 1.10.0 before updating the BIOS to version 1.25.0.

So I was wondering,... 
1. If I go through with the update and go *directly* from 1.5.3 to 1.25.0, skipping 1.10.0, will I brick my device? 
2. Why does `fwupd` not follow this recommendation?

**fwupd version information**
```shell
fwupdmgr --version
runtime   org.freedesktop.fwupd         1.7.9
runtime   com.dell.libsmbios            2.4
compile   org.freedesktop.gusb          0.3.4
compile   com.hughsie.libjcat           0.1.4
runtime   org.kernel                    5.15.0-58-generic
compile   org.freedesktop.fwupd         1.7.9
runtime   org.freedesktop.gusb          0.3.4
```

**Comment by hughsie** [comment]
@CragW is this missing a firmware requirement perhaps?

**Comment by CragW** [comment]
Yeah missing the requirement, I've just added it.

**Comment by CragW** [comment]
@dcd-arnold, if you got a chance to `refresh` metadata then the required minimal version should be there. Thanks for reporting this issue.

**Comment by dcd-arnold** [comment]
@CragW Tank you for the fast response. I don't have access to the computer this weekend, I will check Monday. However,  I just downloaded the `.cab`-file from LVFS, unpacked it with `cabextract` and found:
```
 41   <requires>
 42     <firmware compare="ge" version="1.10.0"/>
 43   </requires>
```
in the `firmware.metainfo.xml`. I guess that is the change you made?

If I look at the current Bios of the 7470, the [Dell Website for Bios version 1.20.0](https://www.dell.com/support/home/en-us/product-support/servicetag/0-NHc2VWxkaDJtOXhrUnphN3hWU3NFQT090/drivers) states:

> If the current BIOS version is earlier than 1.0.2, ensure that you update the BIOS to version 1.5.0 before updating the BIOS to version 1.20.0.

However, when I look into the `.cab` file [from LVFS](https://fwupd.org/lvfs/devices/com.dell.uefib13b7af6.firmware) for the same Model and Bios version, I don't see the same `requires`. Is that missing, too? 

Thank you very much and have a nice weekend,
dcd-arnold

**Comment by dcd-arnold** [comment]
@CragW I did a `fwupdmgr refresh --force` and it shows the latest version again:
```
 $ fwupdmgr update
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade System Firmware from 1.5.3 to 1.24.0?                                ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release fixes the following issues: Firmware updates to 2022     ║
║ Dec platform update.                                                         ║
║                                                                              ║
║ OptiPlex 7460 AIO must remain plugged into a power source for the duration   ║
║ of the update to avoid damage.                                               ║
╚══════════════════════════════════════════════════════════════════════════════╝
```
Maybe I have the package cached?

**Comment by CragW** [comment]
Yup, you have the update candidate listed on your cached metadata. If you proceed to update then the download starts.

**Comment by dcd-arnold** [comment]
@CragW please note, that it now offers `1.24.0` and not `1.25.0`. Maybe because the device fulfills the requirements for `1.24.0` version?

**Comment by CragW** [comment]
The requirement have just been added on the mentioned releases for Optiplex 7460 and Optiplex 7470.

**Comment by dcd-arnold** [comment]
I can verify that upgrades on the 7460 work as expected: I am offered `1.10.0`. I have checke the Bios version `1.7.1` for the 7470, and the requirement is set. Thank you very much!

**Comment by dcd-arnold** [comment]
Hi,

I have tested a 7470 now and `fwupd` crashes with:
```
...
11:05:25:0824 FuEngine             1908 components now in silo
11:05:25:0853 FuEngine             requirement 1.4.6 ge 1.7.9 -> org.freedesktop.fwupd passed
11:05:25:0856 FuDevice             changing verfmt for a45df35ac0e948ee180fe216a5f703f32dda163f: number->dell-bios
11:05:25:0856 FuDevice             changing version for a45df35ac0e948ee180fe216a5f703f32dda163f: 70656->1.20.0
11:05:25:0856 FuDevice             changing version lowest for a45df35ac0e948ee180fe216a5f703f32dda163f: 70656->1.20.0
11:05:25:0859 GLib                 g_strsplit: assertion 'string != NULL' failed
Segmentation fault
```

So I have spun up another 7470 and got the same error. If I remove [the local metadata](https://github.com/fwupd/fwupd#local-metadata) with:
```
rm -rf /var/lib/fwupd/*
rm -rf /usr/share/fwupd/*
```

I can run `fwupd` until I run `fwupdmgr refresh`. I assume this is a regression, hence I am posting this here.

I can not find a `cab` file for version `1.4.6` nor `1.7.9`. Within the `cab` file for `1.20.0`, I cannot find any mention of `a45df35ac0e948ee180fe216a5f703f32dda163f` in `/var/lib/fwupd/` or `/usr/share/fwupd/`. 

Where do I go from here?

**Comment by hughsie** [comment]
> 11:05:25:0859 GLib                 g_strsplit: assertion 'string != NULL' failed

Super uncool. Can you get a backtrace please? i.e. something like `sudo gdb --args /usr/libexec/fwupd/fwupd --verbose` and then when it crashes do `bt` and then dump the output here.

**Comment by dcd-arnold** [comment]
Hi @hughsie,
this is the trace: [gdb.txt](https://github.com/fwupd/firmware-dell/files/10850895/gdb.txt). Anything I can do on my side to help.

**Comment by hughsie** [comment]
@dcd-arnold what's the output for `sudo fwupdtool get-devices -v --plugins uefi-capsule` please

**Comment by hughsie** [comment]
Look what I spy! `<requires><firmware compare="ge" version="1.5.0"/><client/></requires>` -- that looks like a LVFS website issue as the root cause. Debugging now.

**Comment by dcd-arnold** [comment]
> fwupdtool get-devices -v --plugins uefi-capsule

It looks very similar to the error above:
[fwupdtool.txt](https://github.com/fwupd/firmware-dell/files/10851222/fwupdtool.txt)

**Comment by dcd-arnold** [comment]
> Look what I spy! <requires><firmware compare="ge" version="1.5.0"/><client/></requires> -- that looks like a LVFS website issue as the root cause. Debugging now.

@hughsie the error within the data pulled from LVFS still exists for me.

**Comment by hughsie** [comment]
Right, agree -- I'm testing it locally and will deploy it onto the staging env first. I'll take a few hours

**Comment by hughsie** [comment]
@dcd-arnold component 17216 was the only one affected on the production LVFS. The commit was https://gitlab.com/fwupd/lvfs-website/-/commit/65b7e1c77e42aa0774de09d37ded92843ae10859 - if you do "fwupdmgr refresh --force" the issue should be gone. You might need to do `sudo rm /var/lib/fwupd/metadata/lvfs/metadata.xml.xz` to allow the daemon to start.

**Comment by dcd-arnold** [comment]
@hughsie I can confirm that it is working now as expected. Thank you very much.

**Comment by hughsie** [comment]
Phew, thanks for all the help.
