### ISSUE TITLE
Optiplex 3080 "search" showing wrong latest version - remove extraneous leading zeros?

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#164]
LVFS version  search page is showing "1.3.12" the latest:
https://fwupd.org/lvfs/search?value=optiplex+3080

However, clicking the page link *kinda* has the correct version "00.2.17.1" showing. The issue may be in the odd leading zeros? They appear to be extraneous and may be causing the "issue".
The official page does not have the leading zeros:
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=t1yjp&oscode=biosa&productcode=optiplex-3080-desktop

**Comment by CragW** [comment]
@hughsie is this a lvfs-website issue?

**Comment by superm1** [comment]
No nothing to add. I agree drop inf parsing.

**Comment by hughsie** [comment]
Okay, done. https://fwupd.org/lvfs/devices/com.dell.uefi10d19ee4.firmware now shows no leading zeros.

**Comment by pjwelsh** [comment]
Will the "search" part update later? Currently it shows a 1.3.12 version as newest now:
https://fwupd.org/lvfs/search?value=optiplex+3080
Should be the "2.17.1" version.

**Comment by CragW** [comment]
@hughsie Agree with you for the change to `inf` parsing, thanks.

With regarding to the `priority` attribute for a composite device.. the dock BKC turned out is a rich mixture of 3 different docks and each packages has its own version. Perhaps pick one of them as the main representative rather a random subcomponent for now, and see how it goes with the clarity.

**Comment by pjwelsh** [comment]
Please re-open the ticket, the fundamental issue is still apparent - the wrong version is showing as latest when searched:
https://fwupd.org/lvfs/search?value=optiplex+3080
Should show the "2.17.1" version and not the 1.3.12 version shown.

**Comment by hughsie** [comment]
Fixed in the latest LVFS deploy. Thanks all!
