### ISSUE TITLE
LVFS version newer than Dell official somehow for OptiPlex 7010?

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#168]
Dell official has BIOS version 1.1.2
https://www.dell.com/support/home/en-us/product-support/product/optiplex-7010-small-ff/drivers
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=p8jfd&oscode=naa&productcode=optiplex-7010-small-ff

LVFS has 1.2.0 that is newer
https://fwupd.org/lvfs/devices/com.dell.uefi5b31a4ce.firmware

@dell-client-linux:
Did the 1.2.0 version get pulled from official and should be pulled here? Or is the Dell site behind?

**Comment by CragW** [comment]
1.2.0 is a valid release that will be seen on the support page soon.

**Comment by pjwelsh** [comment]
Perfect! Thank you. closing.
