### ISSUE TITLE
Dell Precision 3430 1.29.0

### ISSUE THREAD

**Issue by pix106** [fwupd/firmware-dell#183]
A [link to the firmware update at Dell support](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=ky2fc&oscode=wt64a&productcode=precision-3430-workstation&lwp=rt)

A [link to the previous firmware upgrade at LVFS](https://fwupd.org/lvfs/devices/com.dell.uefid5e264f9.firmware)

The system : Dell Precision 3430

**Comment by CragW** [comment]
@pix106  Can you please verify this issue with the latest metadata?

**Comment by pix106** [comment]
Hi, 1.29.0 is now availaible... and installed here :) Thanks !
