### ISSUE TITLE
XPS 15 9530 (2023)

### ISSUE THREAD

**Issue by Damienhaver** [fwupd/firmware-dell#184]
- A link to the firmware update at Dell support
  - [link](https://www.dell.com/support/home/da-dk/drivers/driversdetails?driverid=2MNG1)
- A link to the previous firmware upgrade at LVFS
  -  There are no updates for the firmware at LVFS
- System
  - Dell XPS 9530 (2023)

**Comment by CragW** [comment]
This platform doesn't support Linux.

**Comment by Damienhaver** [comment]
Sad that this is the official stance of Dell, we can still update our systems firmware directly through the bios, by downloading the .exe, placing it in the esp and update it through the f12 menu, so why not just distribute the firmware through LVFS...

**Comment by dell-client-linux** [comment]
Sorry for the inconvenience, Dell always pursues certify Ubuntu OS on more and more Dell’s products, you could look up the certified devices at: Certified laptops | Ubuntu<https://ubuntu.com/certified/laptops?>.
Unfortunately XPS 15 wasn’t in the list which means the its BIOS wasn’t qualified on Linux, that’s the major reason Dell doesn’t intend to push it to field users.



Internal Use - Confidential
