### ISSUE TITLE
Dell Precision 3430 1.30.0

### ISSUE THREAD

**Issue by pix106** [fwupd/firmware-dell#189]
A [link to the firmware update at Dell support](https://www.dell.com/support/home/fr-fr/drivers/driversdetails?driverid=6v6j1&oscode=wt64a&productcode=precision-3430-workstation)

A [link to the previous firmware upgrade at LVFS](https://fwupd.org/lvfs/devices/com.dell.uefid5e264f9.firmware)

The system : Dell Precision 3430

Thanks !

**Comment by chinyakao** [comment]
Hi @pix106 ,
There is an update on 6/18 and now both websites are 1.30.0. Is this what you are looking for?

**Comment by pix106** [comment]
Yes, I just installed it :)
