### ISSUE TITLE
Dell OptiPlex 3000 Thin Client missing BIOS update 1.21.1

### ISSUE THREAD

**Issue by atw** [fwupd/firmware-dell#198]
System: Dell OptiPlex 3000 Thin Client

Latest LVFS version `1.19.0`
https://fwupd.org/lvfs/devices/com.dell.uefi5a8604b3.firmware

Latest Dell version `1.21.1` from 11 Sep 2024
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=69tkm&oscode=thn8p&productcode=optiplex-3000-thin-client

Previous critical update `1.20.0` from 14 Aug 2024 is also missing on LVFS.
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=htnvf&oscode=thn8p&productcode=optiplex-3000-thin-client

**Comment by CragW** [comment]
It seems they put the latest firmware in various appstreams.
https://fwupd.org/lvfs/search?value=Optiplex+3000
