### ISSUE TITLE
FW update version 1.31.0 missing for Optiplex 7060

### ISSUE THREAD

**Issue by abhi-deshpande** [fwupd/firmware-dell#199]
System - Optiplex 7060 (Tower, SFF, Micro)

Latest firmware version - 1.31.0
[Link](https://www.dell.com/support/home/en-in/drivers/driversdetails?driverid=fnjwn&oscode=wt64a&productcode=optiplex-7060-micro)

LVFS firmware version - 1.29.0
[Link](https://fwupd.org/lvfs/devices/com.dell.uefidf35f706.firmware)

It seems that no firmware updates for this device has been published on LVFS since a couple of quarters.

**Comment by CragW** [comment]
Ubuntu 16.04 reached the end of lifecycle support, try `install_dell_bios_exe.py` instead.

**Comment by abhi-deshpande** [comment]
> Ubuntu 16.04 reached the end of lifecycle support, try `install_dell_bios_exe.py` instead.

Does that mean 7060 would not receive future FW updates via LVFS ?
