### ISSUE TITLE
Missing firmware update 1.4.2 for OptiPlex 7060

### ISSUE THREAD

**Issue by StricUmu** [fwupd/firmware-dell#3]
For missing firmware please provide the following items:

* Link to firmware update at OEM website: https://www.dell.com/support/home/se/sv/sebsdt1/drivers/driversdetails?driverid=TD2NC&oscode=WT64A&productcode=optiplex-7060-desktop

* Firmware release date (if available on OEM website): 2019-07-05

* Link to the device page on LVFS: https://fwupd.org/lvfs/device/com.dell.uefidf35f706.firmware (due to different bug, it's listed as made for 7070 Ultra, but also contains 7060 fw).

**Comment by pjwelsh** [comment]
Not that this is my issue, but the BIOS/firmware for the 7060 looks to have been updated to the most recent 1.8.0.
