### ISSUE TITLE
Unable to update "Dell Inc. System Firmware" as download failed

### ISSUE THREAD

**Issue by gkzz** [fwupd/firmware-dell#35]
This message is the follwoing:

```
Unable to update "Dell Inc. System Firmware" as download failed:
failed to download https://fwupd.org/downloads/-xxxxxxx-d35-XPS_9380_1.11.0.cab: Connection terminated unexpectedlly
```
![Screenshot from 2020-09-08 22-31-08](https://user-images.githubusercontent.com/38461277/92484903-34b1ca00-f225-11ea-935d-84337637477f.png)

All I have to do is download the following file, isn't it??
https://fwupd.org/lvfs/devices/com.dell.uefice945437.firmware

- OS Version
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

-  fwupdmgr Version
```
$ fwupdmgr --version
client version:	1.3.11
compile-time dependency versions
	gusb:	0.3.4
	efivar:	37
daemon version:	1.3.11
```

- hardware info

```
$ sudo lshw -short | head -3
H/W path           Device           Class          Description
==============================================================
                                    system         XPS 13 9380 (08AF)

```

**Comment by hughsie** [comment]
Does it download correctly using `wget` or `curl`?

**Comment by gkzz** [comment]
> Does it download correctly using `wget` or `curl`?

Thanks you for your quick comment!

- I've executed curl command.

```
 curl https://fwupd.org/downloads/60344cbcc1f3c061ea202e1c7d7cc9c6333f0f070eba09fc8ef27114fe3ced35-XPS_9380_1.11.0.cab --output ~/Downloads/xps_9380.cab
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.6M  100 21.6M    0     0  1454k      0  0:00:15  0:00:15 --:--:-- 2711k
```
- I'm successful in it
```
$ ls ~/Downloads/xps_9380.cab 
/home/gkz/Downloads/xps_9380.cab
```
Could you please share your opinion what is the next to do?
Should I run this cab file as follows:

```
$ . /home/gkz/Downloads/xps_9380.cab
```

**Comment by superm1** [comment]
Can you try again in the GUI?  It seems like a transient network issue to me.

**Comment by gkzz** [comment]
> Can you try again in the GUI? It seems like a transient network issue to me.

I appreciate it!

I got the following error message after I clicked `$HOME/Downloads/xps_9380.cab`.

```
Failed to install file: not supported
```

**Comment by superm1** [comment]
I mean try to run the update again pulling from the network not opening the file.  Although that opening the file looks like a different bug..

**Comment by gkzz** [comment]
Thanks for your quick response again.

I tried again over a wired connection, however I got the same problem. 
https://github.com/fwupd/firmware-dell/issues/35#issue-695888292

I have a question.
My question is my issue is the same as [#967](https://github.com/fwupd/fwupd/issues/967) , isn't it??
What do you think so, too?

The following may be good..
https://github.com/fwupd/fwupd/issues/967#issuecomment-515910658
https://github.com/fwupd/fwupd/issues/967#issuecomment-515929474
https://github.com/fwupd/fwupd/issues/967#issuecomment-515929770

**Comment by superm1** [comment]
>I tried again over a wired connection, however I got the same problem.

That's bizarre to me that it worked properly in browser and is failing in Gnome Software.  Do you have a network proxy of some sort that might be influencing?

> My question is my issue is the same as #967 , isn't it??

I don't think so.  Looks like a different error, and that comes from fwupdmgr not gnome-software.

I think you can just run `fwupdmgr install $FILE` for now.

**Comment by gkzz** [comment]
>That's bizarre to me that it worked properly in browser and is failing in Gnome Software. Do you have a network proxy of some sort that might be influencing?

Hmm. I don't use a proxy or anything. .. The network provider may be doing something.

**Comment by gkzz** [comment]
All I have to do is as bellows:

- Get the following cab file
```
$ curl https://fwupd.org/downloads/60344cbcc1f3c061ea202e1c7d7cc9c6333f0f070eba09fc8ef27114fe3ced35-XPS_9380_1.11.0.cab \
> --output $HOME/Downloads/xps_9380.cab
```

- Execute `fwupdmgr install $FILE`

```
$ fwupdmgr install Downloads/xps_9380.cab 
```

- Type y, after the following is displayed.
```
$ fwupdmgr install Downloads/xps_9380.cab 
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Installing on System Firmware…                                   ]
Scheduling…              [***************************************]
Successfully installed firmware

An update requires a reboot to complete. Restart now? [y|N]: 
```
