### ISSUE TITLE
Stale firmware for Latitude 5501

### ISSUE THREAD

**Issue by rzerda** [fwupd/firmware-dell#39]
Hello,

For Latitude 5501 UEFI 1.10.1 is available, but fwupd.org has 1.9.1.

* Dell: https://www.dell.com/support/home/ru-ru/drivers/driversdetails?driverid=9g33w&oscode=wt64a&productcode=latitude-15-5501-laptop
* fwupd.org: https://fwupd.org/lvfs/devices/com.dell.uefi0eecff0c.firmware

**Comment by superm1** [comment]
It's there now.
