### ISSUE TITLE
Missing Firmware: Dell Precision 3431 - 1.6.0

### ISSUE THREAD

**Issue by aburruss** [fwupd/firmware-dell#40]
When filing a request please include the following items:

    A link to the firmware update at Dell support
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=ccc2n&oscode=biosa&productcode=precision-3431-workstation

    A link to the previous firmware upgrade at LVFS
https://fwupd.org/lvfs/devices/com.dell.uefi93a87665.firmware
https://fwupd.org/lvfs/devices/com.dell.uefi2712bb02.firmware

    The system
Dell Precision 3431 Workstation

**Comment by superm1** [comment]
Thanks i'll forward this internally.

**Comment by superm1** [comment]
It's there now, thanks~
