### ISSUE TITLE
Missing BIOS Firmware: OptiPlex 7070 Version 1.7.0

### ISSUE THREAD

**Issue by andre195** [fwupd/firmware-dell#41]
A link to the firmware update at Dell support
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=jyjfc&oscode=biosa&productcode=optiplex-7070-desktop

A link to the previous firmware upgrade at LVFS
https://fwupd.org/downloads/009d16979d0179a990d357983b893b76fc813196038d61598c5726ba9af46a29-Dell_OptiPlex_7070_BIOS_1.5.0.cab

The system
Dell OptiPlex 7070 Desktop

Thanks!

**Comment by superm1** [comment]
Thanks will forward to internal team.

**Comment by andre195** [comment]
All set, see https://fwupd.org/downloads/c09a8f940b54e62f9de0483d956d91fd38a9f3bf14fa890f9519bae41d09badc-Dell_OptiPlex_7070_BIOS_1.7.0.cab

Thanks!
