### ISSUE TITLE
Dell OptiPlex 3040 System BIOS missing 

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#43]
Dell OptiPlex 3040 System BIOS missing 1.12.3 from 13 Jul 2020 marked urgent

https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=xtxyg&oscode=wb64a&productcode=optiplex-3040m-desktop
https://cdn.fwupd.org/lvfs/devices/com.dell.uefid63450d6.firmware

**Comment by superm1** [comment]
I've notified some folks internally to see why this isn't up yet, thanks,

**Comment by superm1** [comment]
It's up now
