### ISSUE TITLE
Dell OptiPlex 5040 System BIOS missing

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#44]
Dell OptiPlex 5040 System BIOS marked urgent 1.16.1 from 10 Sep 2020
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=rhwc4&oscode=biosa&productcode=optiplex-5040-desktop
https://cdn.fwupd.org/lvfs/devices/com.dell.uefi6bd3c333.firmware

**Comment by superm1** [comment]
I've notified some folks internally to see why this isn't up yet, thanks,

**Comment by superm1** [comment]
It's up now
