### ISSUE TITLE
Dell OptiPlex 7040 System BIOS

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#45]
Dell OptiPlex 7040 System BIOS Missing 1.18.0 from 07 Dec 2020 marked Urgent.

https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=v3r24&oscode=biosa&productcode=optiplex-7040-desktop
https://cdn.fwupd.org/lvfs/devices/com.dell.uefib950d63c.firmware

**Comment by superm1** [comment]
I've notified some folks internally to see why this isn't up yet, thanks,

**Comment by superm1** [comment]
It's up now
