### ISSUE TITLE
Missing OptiPlex 5060 firmware

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#55]
Dell site has "URGENT" version 1.9.1:
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=gf9mw&oscode=biosa&productcode=optiplex-5060-desktop

LVFS site has 1.8.0:
https://fwupd.org/lvfs/devices/com.dell.uefifcd78f90.firmware

System:
OptiPlex 5060

**Comment by superm1** [comment]
I've sent a request internally to check on this, thanks.

**Comment by pjwelsh** [comment]
Looks like this firmware has been silently updated at some point to 1.9.1 as expected.
Please close.
