### ISSUE TITLE
Urgent OptiPlex 7040 1.19.0 BIOS missing

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#63]
LVFS latest page 1.18.1 https://fwupd.org/lvfs/devices/com.dell.uefib950d63c.firmware
Dell latest 1.19.0 https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=cc44x&oscode=biosa&productcode=optiplex-7040-desktop
OptiPlex 7040

**Comment by pjwelsh** [comment]
Poke for missing BIOS update.

**Comment by pjwelsh** [comment]
Poke for missing "Urgent" BIOS update.

**Comment by pjwelsh** [comment]
This is odd, the web site shows the 1.18.1 version is latest version, however, the one fwupmgr installed is the correct newer 1.19.0.
Not sure if the version update *just* happened and web page has not yet caught up or what....

**Comment by pjwelsh** [comment]
Sorry, just deleted an extraneous comment as I found out the system had been updated via the install_dell_bios_exe.py tool in this case.

**Comment by pjwelsh** [comment]
Poke for missing "Urgent" BIOS update notice from 1.5 months ago.

**Comment by pjwelsh** [comment]
Appears to have silently been updated. closing.

**Comment by hughsie** [comment]
@pjwelsh thanks for keeping track of these; I appreciate this.
