### ISSUE TITLE
Possibly wrong firmware for Dell XPS 17 9700 and Dell Precision 5750 on fwupd

### ISSUE THREAD

**Issue by spockfish** [fwupd/firmware-dell#66]
Latest firmware for the Dell XPS 17 9700 and Dell Precision 5750 from the Dell download is 1.7.2 (6th of April)

However, on fwupd the lastest firmware is 1.4.0 (https://fwupd.org/lvfs/devices/com.dell.uefi7d606caf.firmware), which firmware version has *never* been released for these 2 models (see history on the official Dell download page). 

'

**Comment by dell-client-linux** [comment]
We have updated the version on fwupd. The latest firmware is [1.7.2](https://fwupd.org/lvfs/devices/com.dell.uefi7d606caf.firmware) now.

**Comment by dell-client-linux** [comment]
Close the issues as it should be resolved.
