### ISSUE TITLE
Dell XPS 15 9550 not detected

### ISSUE THREAD

**Issue by Gelmo** [fwupd/firmware-dell#69]
**Describe the bug**
This issue is the same that was described in issue fwupd/fwupd#2671 

Just wanted to report that I had the same issue today with the same laptop on 1.13.1 (Device ID 2da31270d317b076424992de14a0f08ae373c137 and GUID 124c207d-5db8-4d95-bd31-34fd971b34f9). There still seems to be something interfering that you may want to review for other device owners.

fwupdmgr did not find this as a supported device, even after a forced refresh. I manually installed 1.14.0 via fwupdtool.

After the update to 1.14.0, fwupdmgr still does not see this as a supported device. I submitted a report via get-devices a few hours ago, in case that's helpful.

The Dell site suggests that the latest bios for this is 1.14.0. When searching the GUID on fwupd.org, the results show that the latest version is 1.16.1. Should I attempt to manually install 1.16.1? Is that version not intended for my device? If so, perhaps the listings at fwupd.org need more adjustments. Let me know if there's anything I could provide to assist with this.

**General Info**
```shell
$ sudo fwupdmgr refresh --force
Updating lvfs
Downloading…             [***************************************]
Successfully downloaded new metadata: 0 local devices supported
```

```shell
$ sudo fwupdmgr get-releases
No supported devices
```

**Expected behavior**
The device should be detected and supported, as the GUID is listed at fwupd.org.

**fwupd version information**
```shell
$ fwupdmgr --version
client version:	1.5.8
compile-time dependency versions
	gusb:	0.3.4

daemon version:	1.5.8
```

Installed via Pop OS's default configuration

**fwupd device information**
```shell
$ sudo fwupdmgr get-devices --show-all-devices
XPS 15 9550
│
├─BCM920703 Bluetooth 4.1:
│     Device ID:          23ec719b6aabc2d2dac5176c232f0da7a21881b0
│     Current version:    1.12
│     Vendor:             Broadcom Corp (USB:0x0A5C)
│     Serial Number:      441CA8E1EC60
│     GUIDs:              35fd074d-7c78-599e-b37a-88931c63ba01 ← USB\VID_0A5C&PID_6410&REV_0112
│                         f8498646-6724-5f55-9806-57b3f8636ad8 ← USB\VID_0A5C&PID_6410
│     Device Flags:       • Updatable
│
├─GM107M [GeForce GTX 960M] (XPS 15 9550):
│     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
│     Current version:    a2
│     Vendor:             NVIDIA Corporation (PCI:0x10DE)
│     GUIDs:              5d36a05e-42ad-5b87-8a2d-27b8bd7bfe04 ← PCI\VEN_10DE&DEV_139B&SUBSYS_102806E4&REV_A2
│                         4bbd4dbf-83dd-58ea-a5ad-081ca6f8bca9 ← PCI\VEN_10DE&DEV_139B&SUBSYS_102806E4
│                         995dfa05-5863-56db-8087-221c0cce69a4 ← PCI\VEN_10DE&DEV_139B&REV_A2
│                         2195ad44-2598-565c-819e-16026a8d2f22 ← PCI\VEN_10DE&DEV_139B
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│
├─HD Graphics 530 (XPS 15 9550):
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    06
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              bf3a0b36-1995-5fe3-b81d-9effc018f659 ← PCI\VEN_8086&DEV_191B&SUBSYS_102806E4&REV_06
│                         cc0161dd-f85a-5d3c-8a6f-329aeffd9c55 ← PCI\VEN_8086&DEV_191B&SUBSYS_102806E4
│                         fb0e4398-241c-5c36-ab78-398aa4ed66e5 ← PCI\VEN_8086&DEV_191B&REV_06
│                         be415cfb-b50d-5724-9483-7a56f16d0d70 ← PCI\VEN_8086&DEV_191B
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│
├─Intel(R) Core™ i7-6700HQ CPU @ 2.60GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000e2
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│                         30249f37-d140-5d3e-9319-186b1bd5cac3 ← CPUID\PRO_0&FAM_06
│                         215d01de-fd1a-57cf-9153-72e29c0b7ffe ← CPUID\PRO_0&FAM_06&MOD_5E
│                         c944e5cd-430c-5731-a9d5-c1b63c61cf27 ← CPUID\PRO_0&FAM_06&MOD_5E&STP_3
│     Device Flags:       • Internal device
│
├─System Firmware:
│ │   Device ID:          2da31270d317b076424992de14a0f08ae373c137
│ │   Current version:    1.14.0
│ │   Minimum Version:    1.14.0
│ │   Vendor:             Dell Inc. (DMI:Dell Inc.)
│ │   GUIDs:              124c207d-5db8-4d95-bd31-34fd971b34f9
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│ │                       0d25ab20-f5f1-591f-8baf-c59f009f9548 ← UEFI\RES_{124C207D-5DB8-4D95-BD31-34FD971B34F9}
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │
│ ├─Intel AMT [unprovisioned]:
│ │     Device ID:        e2623122c99d58220498aacbfcfdb1baebbae3c5
│ │     Summary:          Hardware and firmware technology for remote out-of-band management
│ │     Current version:  11.8.70.3626
│ │     Bootloader Version:11.8.70.3626
│ │     Vendor:           Intel Corporation
│ │     GUID:             2800f812-b7b4-2d4b-aca8-46e0ff65814c
│ │     Device Flags:     • Internal device
│ │
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI Revocation Database
│       Current version:  238
│       Minimum Version:  238
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│
├─THNSN5256GPU7 NVMe TOSHIBA 256GB:
│     Device ID:          04e17fcf7d3de91da49a163ffe4907855c3648be
│     Summary:            NVM Express Solid State Drive
│     Current version:    57DA4103
│     Vendor:             Toshiba Corporation (NVME:0x1179)
│     Serial Number:      Z5HS1057T5XV
│     GUIDs:              2060b01b-f6aa-5fea-9acd-804de1765920 ← NVME\VEN_1179&DEV_010F&SUBSYS_11790001&REV_01
│                         87178ed9-f82b-5895-bcb0-09713abc842c ← NVME\VEN_1179&DEV_010F&SUBSYS_11790001
│                         e22c4520-43dc-5bb3-8245-5787fead9b63 ← NVME\VEN_1179&DEV_010F&REV_01
│                         83991323-9951-5adf-b743-d93e882a41e1 ← NVME\VEN_1179&DEV_010F
│                         e3bd41c3-0013-52e9-bf56-dafc0c2ae333 ← THNSN5256GPU7 NVMe TOSHIBA 256GB
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│
└─TPM 1.2:
  │   Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
  │   Summary:            Platform TPM device
  │   Current version:    5.81.0.0
  │   Vendor:             Dell Inc. (PCI:0x1028)
  │   Update Error:       Updating disabled due to TPM ownership
  │   GUIDs:              9055a777-a92f-55da-8d34-6614d8f9df92 ← 06e4-1.2
  │                       ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
  │   Device Flags:       • Internal device
  │                       • System requires external power source
  │
  ├─Event Log:
  │     Device ID:        58bd405f31c48e6eca290b425f530a94c91e955c
  │     GUID:             a25657fe-b5dc-5be0-8b78-8b9dfec678ff ← system-tpm-eventlog
  │     Device Flags:     • Internal device
  │
  └─TPM 2.0:
        Device ID:        04d075f2971403e31c1dbdf3b38f709d7c2e749d
        Summary:          Alternate mode for platform TPM device
        Update Error:     mode switch disabled due to TPM ownership
        GUID:             75305a8e-596f-5a3b-9aea-ebee36dc585e ← 06e4-2.0
        Device Flags:     • Internal device
                          • System requires external power source
                          • Device is locked
```

**System UEFI configuration**
```shell
$ sudo efibootmgr -v
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0002,0001
Boot0000* Pop!_OS 20.10	HD(1,GPT,ffa81c18-7174-4f6f-9cd5-1e11f71c131f,0x1000,0xf8fff)/File(\EFI\SYSTEMD\SYSTEMD-BOOTX64.EFI)
Boot0001* Linux Firmware Updater	HD(1,GPT,ffa81c18-7174-4f6f-9cd5-1e11f71c131f,0x1000,0xf8fff)/File(\EFI\pop\fwupdx64.efi)
Boot0002* UEFI: THNSN5256GPU7 NVMe TOSHIBA 256GB, Partition 1	HD(1,GPT,ffa81c18-7174-4f6f-9cd5-1e11f71c131f,0x1000,0xf8fff)/File(EFI\boot\bootx64.efi)..BO
```

```shell
$ sudo efivar -l | grep fw
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-124c207d-5db8-4d95-bd31-34fd971b34f9-0
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-ux-capsule
```

```shell
$ sudo tree /boot
/boot
├── config-5.11.0-7612-generic
├── config-5.11.0-7614-generic
├── efi
│   ├── 7c32b39c1ea38e542977af8a5ed7ce2e
│   ├── EFI
│   │   ├── BOOT
│   │   │   └── BOOTX64.EFI
│   │   ├── Dell
│   │   │   ├── Bios
│   │   │   │   └── Recovery
│   │   │   │       ├── BIOS_CUR.RCV
│   │   │   │       └── BIOS_PRE.rcv
│   │   │   └── logs
│   │   │       ├── diags_current.xml
│   │   │       └── diags_previous.xml
│   │   ├── Linux
│   │   ├── pop
│   │   │   ├── fw
│   │   │   │   ├── fwupd-124c207d-5db8-4d95-bd31-34fd971b34f9.cap
│   │   │   │   └── fwupd-3b8c8162-188c-46a4-aec9-be43f1d65697.cap
│   │   │   └── fwupdx64.efi
│   │   ├── Pop_OS-a3ca2e22-e485-4806-91cb-03418f43e4b1
│   │   │   ├── cmdline
│   │   │   ├── initrd.img
│   │   │   ├── initrd.img-previous
│   │   │   ├── vmlinuz.efi
│   │   │   └── vmlinuz-previous.efi
│   │   ├── Recovery-DA8B-2159
│   │   │   ├── initrd.gz
│   │   │   └── vmlinuz.efi
│   │   └── systemd
│   │       └── systemd-bootx64.efi
│   └── loader
│       ├── entries
│       │   ├── Pop_OS-current.conf
│       │   ├── Pop_OS-oldkern.conf
│       │   └── Recovery-DA8B-2159.conf
│       ├── loader.conf
│       └── random-seed
├── initrd.img -> initrd.img-5.11.0-7614-generic
├── initrd.img-5.11.0-7612-generic
├── initrd.img-5.11.0-7614-generic
├── initrd.img-5.3.0-7642-generic
├── initrd.img.old -> initrd.img-5.11.0-7612-generic
├── System.map-5.11.0-7612-generic
├── System.map-5.11.0-7614-generic
├── vmlinuz -> vmlinuz-5.11.0-7614-generic
├── vmlinuz-5.11.0-7612-generic
├── vmlinuz-5.11.0-7614-generic
└── vmlinuz.old -> vmlinuz-5.11.0-7612-generic

16 directories, 34 files
```

**Additional questions**
- Operating system and version: Pop OS (tested on 20.04 and 20.10)
- Have you tried rebooting? Yes.
- Is this a regression? Perhaps; issue fwupd/fwupd#2671 suggests that this was previously corrected.
- Are you using an NVMe disk? Yes.
- Is secure boot enabled? No.
- Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS? No.

**Comment by GoPerry** [comment]
> Since the BIOS cab is built by automation and presumably the XPS version isn't supposed to have more updates it might be an easier process to rename the ID on all the old ones that apply to both to me.

Mario.
So 

> OK I think I found what's going on. If you look at the stable metadata, you can see that
> 
> ```
>     <requires>
>       <hardware>d98dc575-9143-5a8f-a620-9440ef640c8d</hardware>
>     </requires>
> ```
> 
> Is set for the device in `firmware.xml.gz` _not_ in the **release**. So it is applied to _all_ releases.
> 
> ```
>       <release version="68354" timestamp="1564495178" urgency="critical">
>         <location>https://fwupd.org/downloads/8d16ce33cf73505dfc76ff7609ed2909ffcb79ee-Precision_5510_1.11.2.cab</location>
>         <checksum type="sha1" filename="8d16ce33cf73505dfc76ff7609ed2909ffcb79ee-Precision_5510_1.11.2.cab" target="container">767bec5099a9ce9278ee95860fd64018af1617d5</checksum>
>         <checksum type="sha256" filename="8d16ce33cf73505dfc76ff7609ed2909ffcb79ee-Precision_5510_1.11.2.cab" target="container">257a690baf81eec1ef98e5e57c31aede3055e5f6547c22629f99795d5ebba6d3</checksum>
>         <checksum type="sha1" filename="firmware.bin" target="content">8e335187c2946574c103b0e44dc5d6747416e0ac</checksum>
>         <checksum type="sha256" filename="firmware.bin" target="content">3e571e0b81239b23f33f59717541c447aa794bbea0c32f656c8b688fd5422463</checksum>
>         <description>
>           <p>This stable release fixes the following issues:</p>
>           <ul>
>             <li>Fixed the issue where the TPM option disappears from the BIOS setup menu intermittently.</li>
>           </ul>
>         </description>
>         <size type="installed">10240280</size>
>         <size type="download">10260780</size>
>         <artifacts>
>           <artifact type="binary">
>             <location>https://fwupd.org/downloads/8d16ce33cf73505dfc76ff7609ed2909ffcb79ee-Precision_5510_1.11.2.cab</location>
>             <filename>Precision_5510_1.11.2.cab</filename>
>             <checksum type="sha1">767bec5099a9ce9278ee95860fd64018af1617d5</checksum>
>             <checksum type="sha256">257a690baf81eec1ef98e5e57c31aede3055e5f6547c22629f99795d5ebba6d3</checksum>
>             <size type="installed">10240280</size>
>             <size type="download">10260780</size>
>           </artifact>
>         </artifacts>
>       </release>
>     </releases>
>     <requires>
>       <hardware>d98dc575-9143-5a8f-a620-9440ef640c8d</hardware>
>     </requires>
>   </component>
> ```

Hi Mario.
So the fix will be that move the <hardware> section to release section like this ?
Is it correct ?


      <release version="68354" timestamp="1564495178" urgency="critical">
      .....skip....
   ++ <hardware>d98dc575-9143-5a8f-a620-9440ef640c8d</hardware>
    </releases>


    <requires>
   -- <hardware>d98dc575-9143-5a8f-a620-9440ef640c8d</hardware>
    </requires>

**Comment by GoPerry** [comment]
Hi Mario.
So the fix will be that move the <hardware> section to release section like this ?
Is it correct ?

      <release version="68354" timestamp="1564495178" urgency="critical">
      .....skip....
       ++ <hardware>d98dc575-9143-5a8f-a620-9440ef640c8d</hardware>
    </releases>

    <requires>
   -- <hardware>d98dc575-9143-5a8f-a620-9440ef640c8d</hardware>
    </requires>

**Comment by superm1** [comment]
@GoPerry the fix is is to change the appstream ID, ie what is going into the top as `com.dell.uefiXXXXXX`

**Comment by superm1** [comment]
Because it's built by automation on the Dell side - I would suggest change appstream ID on all the older ones to something common instead.

**Comment by GoPerry** [comment]
> @GoPerry the fix is is to change the appstream ID, ie what is going into the top as `com.dell.uefiXXXXXX`

Hi Mario.
Because I have no access the to automation build server, I would need to check with team
It is clear what we should fix now.

Thanks  a lot !

**Comment by superm1** [comment]
At least my experience with how that works I think it's easier to just fixup all old releases on lvfs than changing build server, but up to you which way to go!

**Comment by JoeyCorleone** [comment]
After refreshing the metadata, fwupmgr now suggests a BIOS update:

`Upgrade System Firmware from 1.14.0 to 1.22.0?`

However, on the DELL website, 1.14 is still the [latest available version](https://www.dell.com/support/home/en-us/product-support/product/xps-15-9550-laptop/drivers) for the XPS 9550.

In the get-updates summary, both XPS 15 9550 and Precision 5510 are mentioned:

`├─XPS 15 9550/Precision 5510:
  │     New version:      1.22.0
  │     Remote ID:        lvfs
  │     Release ID:       14400
  │     Summary:          Firmware for the Dell XPS 15 9550/Precision 5510
  │     License:          Proprietary
  │     Size:             13,4 MB
  │     Created:          2022-06-06
  │     Urgency:          High
  │     Vendor:           Dell
  │     Release Flags:    • Is upgrade
  │     Description:      
  │     This stable release fixes the following issues:
  │     
  │     • Improved the system stability.
`

Is it correct to assume that the update is safe because it is offered by fwupdmgr?

**Comment by chinyakao** [comment]
Hi @JoeyCorleone,

XPS 15 9550, Berlinetta was EOS on 2020/3/31. And due to Berlinetta P, and Berlinetta use same BIOS package, when we submit the latest BIOS package to LVFS, it also show the info of xml. 
We have remove the tag of XPS 15 9550 from the latest BIOS 1.22.0.

Thank you

**Comment by chinyakao** [comment]
Hi @JoeyCorleone 
They have fixed the filename for Precision 5510 release to avoid confusion.
