### ISSUE TITLE
XPS 13 9310 2-in-1 is missing latest update addressing critical security vulnerabilities

### ISSUE THREAD

**Issue by Esokrates** [fwupd/firmware-dell#72]
As you can see here:

https://fwupd.org/lvfs/devices/com.dell.uefia472a89c.firmware

it shows 2.2.1 as being the latest version, while the real latest version is 2.3.3 released 5 days ago and containing security critical fixes:

https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=xy1ww&oscode=wt64a&productcode=xps-13-9310-2-in-1-laptop

Please make sure the latest version is uploaded.

**Comment by CragW** [comment]
**XPS 9310 2-in-1** doesn't support Ubuntu hence no firmware uploads for fwupd/LVFS.
https://www.dell.com/support/home/en-us/product-support/product/xps-13-9310-2-in-1-laptop/drivers

The latest system firmware for **XPS 9310** is 3.6.0:
https://fwupd.org/lvfs/devices/com.dell.uefiecfae66b.firmware

Same as Windows' offering:
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=10w50&oscode=ubt20&productcode=xps-13-9310-laptop
