### ISSUE TITLE
Dell Precision 5550 System BIOS Urgent update 1.8.1

### ISSUE THREAD

**Issue by daolis** [fwupd/firmware-dell#74]
**Dell Firmware**: Urgent, Security fixes
https://www.dell.com/support/home/de-at/drivers/driversdetails?driverid=kkwfn&oscode=biosa&productcode=precision-15-5550-laptop
**LVFS**: https://fwupd.org/lvfs/devices/com.dell.uefi57bd7271.firmware
**System**: Dell Precision 5550

**Comment by dell-client-linux** [comment]
The FW is update to latest version (1.8.1) on LVFS.
