### ISSUE TITLE
Missing Dell Precision 3431 System BIOS Urgent update 1.8.4

### ISSUE THREAD

**Issue by aburruss** [fwupd/firmware-dell#80]
When filing a request please include the following items:

A link to the firmware update at Dell support

https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=rkvp1&oscode=biosa&productcode=precision-3431-workstation

A link to the previous firmware upgrade at LVFS

https://fwupd.org/lvfs/devices/com.dell.uefi93a87665.firmware
https://fwupd.org/lvfs/devices/com.dell.uefi2712bb02.firmware

The system

Dell Precision 3431 Workstation

Need urgent update 1.8.4 added to LVFS, please.

**Comment by dell-client-linux** [comment]
1.8.4 has been added to LVFS. 
Thanks.
