### ISSUE TITLE
OptiPlex 3040 Urgent BIOS update 1.17.1

### ISSUE THREAD

**Issue by pjwelsh** [fwupd/firmware-dell#89]
LVFS version  1.14.2
https://fwupd.org/lvfs/devices/com.dell.uefid63450d6.firmware
Dell version 27 Aug 2021 1.16.1
https://www.dell.com/support/home/en-us/product-support/product/optiplex-3040m-desktop/drivers

**Comment by pjwelsh** [comment]
Any word on update? 2 "Urgent" BIOS updates have been missed now (1.15.2 and 1.16.1):
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=rmxgj&oscode=wb64a&productcode=optiplex-3040m-desktop

**Comment by pjwelsh** [comment]
Just a reminder that this urgent BIOS needs to be updated.
Thanks

**Comment by pjwelsh** [comment]
The newest is now 1.17.1: https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=nktdf&oscode=wb64a&productcode=optiplex-3040m-desktop
This is now the *third* "Urgent" BIOS update for this product line not yet provided to fwupd.
Can one of the Dell people make some effort into correcting this situation, please.

**Comment by hughsie** [comment]
@dell-client-linux is there a problem we can help with?

**Comment by pjwelsh** [comment]
Please update this long missing system's BIOS.

**Comment by pjwelsh** [comment]
Also/FYI, not sure if you caught the release info or not, but Dell has also *just* released a very large number of additional "Urgent" BIOS updates since yesterday.

**Comment by pjwelsh** [comment]
Looks like this got silently updated :( 
closing.
